apiVersion: v1
kind: Service
metadata:
  name: g9-minio-console
  namespace: minio
  labels:
    app: minio
    app.kubernetes.io/name: g9-minio-console
spec:
  type: NodePort
  selector:
    app: minio
  ports:
    - name: console
      port: 9001
      targetPort: 9001
      nodePort: 30901
      protocol: TCP
